Repository nervosnetwork/ckb-sdk-go, pull requests merged in 2022-12, with the labels that each got.

#176 chore: add case for getting rejected tx
  rpc/client_test.go
Labels: chore

#174 Add RPC method `EstimateCycles`
  rpc/client.go
  rpc/client_test.go
  types/chain.go
  types/json.go
Labels: feature

#179 chore: updates doc/examples about CKB-Indexer RPC
  README.md
  indexer/indexer_test.go
Labels: documentation
